### PR TITLE
remove underscore dependency and add relative path support for @import

### PR DESCRIPTION
**Pull request by aunz**
Hello Chris,
This is my first open source contributing, so bear with me!

### CODE REVIEW

**Comment by cwaring** [comment]
Hi @aunz,

Thanks for the contribution and extra credits for reading the docs and calling your branch 'my-new-feature' ;)

Do you have problems importing relative files using the following path: `@import './mycssfile';`?

**Comment by aunz** [comment]
Hello Chris,

Initially, when using `getDisplayPath()`, I couldn't get `@import './mycssfile'` to work.

After some researching, I found that `getDisplayPath()` adds a leading slash `/` to `{from:'/somepath'}`, that's why `@import` didn't work.

By changing to `getPathInPackage()`, the leading slash `/` is no longer there and `@import` works as expected even with `../otherpath/othercss`

According to http://cssnext.io/usage/#from, the from is `{from:"./somefile"}`

So for `@import` to work, either using `./` or no `/`

**Comment by cwaring** [comment]
Great. I've tested this locally and it works perfectly. I think `getDisplayPath()` was an overhang from pre Meteor 1.2, I'll merge now and release an update. Thanks again for helping out :+1:

**Comment by aunz** [comment]
Thanks for the opportunity. It was my first open source contribution using git pull request. The experience was very satisfying!

**Pull request merged**
